//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.42
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------



[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
[System.ServiceModel.ServiceContractAttribute(Namespace="http://strangelights.com/FSharp/Foundations/WCFImageService", ConfigurationName="IImageService")]
public interface IImageService
{
    
    [System.ServiceModel.OperationContractAttribute(Action="http://strangelights.com/FSharp/Foundations/WCFImageService/IImageService/Receive" +
        "Image", ReplyAction="http://strangelights.com/FSharp/Foundations/WCFImageService/IImageService/Receive" +
        "ImageResponse")]
    void ReceiveImage(byte[] image);
}

[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public interface IImageServiceChannel : IImageService, System.ServiceModel.IClientChannel
{
}

[System.Diagnostics.DebuggerStepThroughAttribute()]
[System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
public partial class ImageServiceClient : System.ServiceModel.ClientBase<IImageService>, IImageService
{
    
    public ImageServiceClient()
    {
    }
    
    public ImageServiceClient(string endpointConfigurationName) : 
            base(endpointConfigurationName)
    {
    }
    
    public ImageServiceClient(string endpointConfigurationName, string remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(endpointConfigurationName, remoteAddress)
    {
    }
    
    public ImageServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
            base(binding, remoteAddress)
    {
    }
    
    public void ReceiveImage(byte[] image)
    {
        base.Channel.ReceiveImage(image);
    }
}
